version: "3"

services:
  tiddi:
    image: ghcr.io/kunalsin9h/tiddi-container:latest
    ports:
      - "5656:5656"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PORT: 5656
      DB: ./database/prod.db
      HOST: https://tiddi.kunalsin9h.com
    volumes:
      - ./database/prod.db/:/tiddi/database/prod.db

  tiddi-demo:
    image: ghcr.io/kunalsin9h/tiddi-container:latest
    ports:
      - "5657:5657"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PORT: 5657
      DB: ./database/demo.db
      HOST: https://tiddi-demo.kunalsin9h.com
    volumes:
      - ./database/demo.db/:/tiddi/database/demo.db
