name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          make build
      - name: Push
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.GHCR }}" | docker login ghcr.io -u "kunalsin9h" --password-stdin
          docker push ghcr.io/kunalsin9h/tiddi-container:latest
